name: Build and push docker image

on:
  push:
    branches:
      - branchHTTPserver

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          paltform: amd64, arm64

      - name: Set up docker buildx
        user: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            vasylbulak/httpserver:latest
            vasylbulak/httpserver:${{ github.sha }}
          platforms: linux/amd64, linux/arm64
